version: '3'

services:
  web:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - "../:/srv"
      - "~/.ssh:/root/.ssh"
    ports:
      - "2015:2015"
    links:
      - db
      - redis
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homedash
      MYSQL_USER: homedash
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306"
  redis:
    image: redis:4.0-alpine
    ports:
      - "6379"
